WebApplication1/Models/ErrorViewModel.cs
using System;

namespace WebApplication1.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebApplication1/Models/MayTinhModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication1.Controllers
{
    public class MayTinhModel
    {
        public double So1 { get; set; }
        public double So2 { get; set; }
        public string PhepTinh { get; set; }
        public double KetQua()
        {
            double ketqua = 0;
            switch (PhepTinh)
            {
                case "+": ketqua = So1 + So2; break;
                case "-": ketqua = So1 - So2; break;
                case "*": ketqua = So1 * So2; break;
                case "/": ketqua = So1 / So2; break;
            }
            return ketqua;
        }
    }
}

WebApplication1/Models/PersonModel.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication1.Models
{
    public class PersonModel : Controller
    {
        public int Id { get; set; }
        public string FullName { get; set; }
        public string BirthDay { get; set; }
        public string Picture { get; set; }

    }
}

WebApplication1/Controllers/GioiThieuController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication1.Controllers
{
    public class GioiThieuController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult BanThan()
        {
            return View();
        }
        public IActionResult ChaMe()
        {
            return View();
        }
        public IActionResult AnhChiEm()
        {
            return View();
        }
    }
}

WebApplication1/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }
        
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebApplication1/Controllers/MayTinhController.cs
using Microsoft.AspNetCore.Mvc;
using WebApplication1.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication1.Controllers
{
    public class MayTinhController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        //Minh họa 1: Tiếp nhận tham số thông qua Reques
        //public IActionResult XuLy()
        //{
        //    //b1.Lấy giá trị các tham số (So1, So2, phep tinh)
        //    var x = double.Parse(Request.Form["So1"]);
        //    var y = double.Parse(Request.Form["So2"]);
        //    var op = Request.Form["PhepTinh"];
        //    //b2. Tính toán kết quả
        //    double Ketqua = 0;
        //    switch (op)
        //    {
        //        case "+": Ketqua = x + y; break;
        //        case "-": Ketqua = x - y; break;
        //        case "*": Ketqua = x * y; break;
        //        case "/": Ketqua = x / y; break;
        //    }
        //    //b3.Trả kết quả về người dùng
        //    ViewData["KQ"] = Ketqua;
        //    ViewBag.KQ = Ketqua;
        //    return View("XuLy");
        //}

        //Minh họa 2: Tiếp nhận tham số thông qua đối số của action
        //public IActionResult XuLy(double So1, double So2, string PhepTinh)
        //{
        //    //b1.Lấy giá trị các tham số (So1, So2, phep tinh)
        //    //b2. Tính toán kết quả
        //    double Ketqua = 0;
        //    switch (PhepTinh)
        //    {
        //        case "+": Ketqua = So1 + So2; break;
        //        case "-": Ketqua = So1 - So2; break;
        //        case "*": Ketqua = So1 * So2; break;
        //        case "/": Ketqua = So1 / So2; break;
        //    }
        //    //b3.Trả kết quả về người dùng
        //    //ViewData["KQ"] = Ketqua;//Truyền dữ liệu cho view thông qua viewdata
        //    ViewBag.KQ = Ketqua;//Truyền dữ liệu cho view thông qua viewbag
        //    return View();
        //}

        //Minh họa 3: Tiếp nhận tham số thông qua Model
        public IActionResult XuLy(MayTinhModel mt)
        {
            //b1.Lấy giá trị các tham số (So1, So2, phep tinh)
            //b2. Tính toán kết quả
            double ketqua = 0;
            switch(mt.PhepTinh)
            {
                case "+": ketqua = mt.So1 + mt.So2; break;
                case "-": ketqua = mt.So1 - mt.So2; break;
                case "*": ketqua = mt.So1 * mt.So2; break;
                case "/": ketqua = mt.So1 / mt.So2; break;
            }
            //b3.Trả kết quả về người dùng
            //ViewData["KQ"] = Ketqua;//Truyền dữ liệu cho view thông qua viewdata
            ViewBag.KQ = mt.KetQua();//Truyền dữ liệu cho view thông qua viewbag
            return View("Index",mt);
        }
    }
}

WebApplication1/Controllers/RegisterController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebApplication1.Models;
using System.IO;

namespace WebApplication1.Controllers
{
    public class RegisterController : Controller
    {
        private readonly IHostingEnvironment hosting;
        public RegisterController(IHostingEnvironment _hosting)
        {
            hosting = _hosting;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult XuLy(PersonModel m, IFormFile FHinh)
        {
            
            if (FHinh !=null)
            {
                //Xử lý upload
                //string filename = FHinh.FileName;
                string filename = Guid.NewGuid().ToString() + Path.GetExtension(FHinh.FileName);
                string path = Path.Combine(hosting.WebRootPath, "images");
                using (var filestream = new FileStream(Path.Combine(path, filename), FileMode.Create))
                {
                    //Sao chép lên Server
                    FHinh.CopyTo(filestream);
                }
                
                m.Picture = filename;

            }
            return View(m);
        }
    }
}

WebApplication1/Views/GioiThieu/AnhChiEm.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<div class="alert alert-info pt-2">
    Thông tin Anh chị em của tôi
</div>

<div class="mt-2">
    Họ tên Anh: <br>
    Ngày Sinh: <br>
    Sở thích: <br>
</div>
<div class="mt-2">
    Họ tên Chị: <br>
    Ngày Sinh: <br>
    Sở thích: <br>
</div>

WebApplication1/Views/GioiThieu/BanThan.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<div class="alert alert-info pt-2">
    Họ Tên tướng: LeeSin <br>
    Ngày Sinh: <br>
    Sở Thích: <br>
</div>

WebApplication1/Views/GioiThieu/ChaMe.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<div class="alert alert-info pt-2">
    Thông tin cha me của tôi
</div>

<div class="mt-2">
    Họ tên Cha: <br>
    Ngày Sinh: <br>
    Sở thích: <br>
</div>
<div class="mt-2">
    Họ tên Mẹ: <br>
    Ngày Sinh: <br>
    Sở thích: <br>
</div>

WebApplication1/Views/GioiThieu/Index.cshtml
<div>
    <h2>Chào bạn đã đến bình nguyên vô tận</h2>
    <div>
        Arena of valor
    </div>

    <ul>
        <li> <a asp-controller="GioiThieu" asp-action="BanThan">Thông tin bản thân </a></li>
        <li> <a asp-controller="GioiThieu" asp-action="ChaMe">Thông tin cha mẹ</a></li>
        <li> <a asp-controller="GioiThieu" asp-action="AnhChiEm">Thông tin anh chị em</a> </li>
    </ul>
</div>

WebApplication1/Views/Home/Index.cshtml
<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

WebApplication1/Views/MayTinh/Index.cshtml
@model MayTinhModel
<h2>Tính toán đơn giản</h2>
<hr />
<form asp-action="XuLy" method="post" enctype="multipart/form-data">
    
    <div class="form-group">
        <label>Nhập số thứ 1</label>
        <input asp-for="So1" class="form-control" />
    </div>
    <div class="form-group">
        <label>Nhập số thứ 2</label>
        <input asp-for="So2" class="form-control" />
    </div>
    <div class="form-group">
        <label>Chọn phép tính</label>
        <select name="PhepTinh" class="form-control">
            <option value="+">Cộng</option>
            <option value="-">Trừ</option>
            <option value="*">Nhân</option>
            <option value="/">Chia</option>
        </select>
    </div>
    <button type="submit" class="btn btn-danger">Tính</button>
</form>

@if (Model.Ketqua.KQ != null)
            {
                <h4 class="pt-2">Kết quả: @ViewBag.KQ</h4>
            }

WebApplication1/Views/MayTinh/XuLy.cshtml
<h2>Kết quả tính toán: @ViewData["KQ"]</h2>

WebApplication1/Views/Register/Index.cshtml
@model PersonModel
<h2>Thông Tin Đăng Ký</h2>
<hr />
<form asp-action="XuLy" method="post" enctype="multipart/form-data">
    <div class="form-group">
        <label>Họ tên</label>
        <input asp-for="FullName" class="form-group" />
    </div>
    <div class="form-group">
        <label>Ngày sinh</label>
        <input asp-for="BirthDay" type="date" class="form-group" />
    </div>
    <div class="form-group">
        <label>Hình đại diện</label>
        <input name="FHinh" type="file" class="form-control" />
    </div>
    <button type="submit" class="btn btn-danger">Đăng Ký</button>
</form>

WebApplication1/Views/Register/XuLy.cshtml
@model PersonModel

<h3>Thông Tin Đăng Ký</h3>
<hr />
<ul>
    <li>Họ tên: @Model.FullName </li>
    <li>Ngày sinh: @Model.BirthDay </li>
    <li>Hình đại diện: <br>   
        <img src="/images/@Model.Picture" width="200px" />
    </li>
</ul>

WebApplication1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewBag["Title"] - WebApplication1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebApplication1</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="XuLy" asp-action="Index">Máy Tính</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="XuLy" asp-action="Index">Register</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Register" asp-action="Index">Register</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - WebApplication1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: true)

</body>
</html>